name: Base PR

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  base-pr:
    if: github.repository != 'vinkashq/base'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: "base"
          fetch-depth: 0
      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/vinkashq/base.git
          git fetch upstream
      - name: Merge Upstream
        run: |
          git merge upstream/main
          git push origin base
      - name: Create PR
        run: |
          gh pr create --title "Merge base changes" --body "Auto PR for Upstream Changes" --base main --head base
